Add phone number confirmation feature
WebiksInc/CTF pull request #4
Opened 2024-12-10 17:05 UTC by tomerp20

Currently the PR contains all needed changes in backend code. We are waiting for the designer in order to proceed with frontend work.

2024-12-11 13:31 UTC, amit-sha-webiks commented
looks great!

2024-12-11 14:33 UTC, shacharmo commented on CTFd/api/v1/challenges.py
> +        if challenge.phone_verification_required == True :
I thinks it's better to use a decorator if possible like `@require_verified_emails`, also note that everywhere that `@require_verified_emails` is used check if phone validation is relevant

2024-12-11 14:36 UTC, shacharmo commented on CTFd/utils/validators/__init__.py
> +    pattern_zero_prefix = r"^05[2-9]\d{7}$"  # Matches 0... mobile format
Should be more restricted, see:
https://en.wikipedia.org/wiki/Telephone_numbers_in_Israel

Also, shouldn't dashes be allowed?

2024-12-12 08:35 UTC, tomerp20 commented on CTFd/api/v1/challenges.py
> +        if challenge.phone_verification_required == True :
I agree about the decorator, will implement it in the future when there will be more cases where it's needed.

2024-12-12 13:59 UTC, tomerp20 commented on CTFd/utils/validators/__init__.py
> +    pattern_zero_prefix = r"^05[2-9]\d{7}$"  # Matches 0... mobile format
I added support for "-" inside the phone number in the  05XXXXXXXX format.
Regarding making the regex stricter, did you mean to block 056 & 059 prefix since they are not israeli?

2024-12-15 07:41 UTC, shacharmo commented on CTFd/api/v1/challenges.py
> +        if challenge.phone_verification_required == True :
Please check now the usage of `@require_verified_emails` and make sure all endpoints that require phone validation are secured

2024-12-15 07:42 UTC, shacharmo commented on CTFd/utils/validators/__init__.py
> +    pattern_zero_prefix = r"^05[2-9]\d{7}$"  # Matches 0... mobile format
Yes, the validation should be accurate

2024-12-15 08:31 UTC, tomerp20 commented on CTFd/utils/validators/__init__.py
> +    pattern_zero_prefix = r"^05[2-9]\d{7}$"  # Matches 0... mobile format
fixed

2024-12-15 09:58 UTC, tomerp20 commented on CTFd/api/v1/challenges.py
> +        if challenge.phone_verification_required == True :
done

2024-12-15 13:37 UTC, shacharmo requested changes
Do we use CTFd tokens (CTFd/api/v1/tokens.py)? If so, probably need to check if requires phone verification (token is for a stage that requires it)

Do we use unlocks (CTFd/api/v1/unlocks.py)? If so, probably need to check if requires phone verification (if hint is for a stage that requires it)

2024-12-15 13:37 UTC, shacharmo commented on CTFd/utils/decorators/__init__.py
> -        if get_config("verify_emails"):
Why remove? Are emails always needed to be verified in the platform? Think about closed environment usages

2024-12-15 13:37 UTC, shacharmo commented on CTFd/utils/validators/__init__.py
> +    pattern_zero_prefix = r"^05[01234578]-?\d{7}$"  # Matches 0... mobile format with optional -
You can easily combine to a single regex

2024-12-15 13:37 UTC, shacharmo commented on CTFd/api/v1/challenges.py
`class ChallengeSolves(Resource)` is not protected

2024-12-15 16:03 UTC, tomerp20 commented on CTFd/utils/validators/__init__.py
> +    pattern_zero_prefix = r"^05[01234578]-?\d{7}$"  # Matches 0... mobile format with optional -
fixed

2024-12-15 16:09 UTC, tomerp20 commented on CTFd/utils/decorators/__init__.py
> -        if get_config("verify_emails"):
I agree, didn't think thought this through

2024-12-15 16:28 UTC, tomerp20 commented on CTFd/api/v1/challenges.py
I see, but since it only contains 1 function which us protected (get), what does difference does it make?

2024-12-15 16:30 UTC, tomerp20 commented
Regarding tokens & unblocks - We need to ask Lior about this feature in terms if necessity and security in order to determine how to handle this. I  will bring it to the conversation in tomorrow's daily.

2024-12-15 16:38 UTC, shacharmo requested changes

2024-12-15 16:38 UTC, shacharmo commented on CTFd/api/v1/challenges.py
It check if challenge is solved (if I understand correctly), we should protect it

2025-04-24 08:43 UTC, closed without merging