Add user active stage check and enhance logging functionality
WebiksInc/CTF pull request #5
Opened 2024-12-16 07:53 UTC by tomerp20

This PR contains initial setup for monitoring and logging login for this user events:
Registration 
Login
Logout
Start Stage
End Stage - fail: wrong flag
End Stage - success
Rate limit Exceeding on stage solve attempt

The PR reference's to this trello ticket:
https://trello.com/c/xhrH0K8K/81-track-users-event-from-ctfd-into-opensearch

2024-12-16 09:14 UTC, amit-sha-webiks commented
looking GOOD :)

2024-12-16 20:04 UTC, shacharmo requested changes

2024-12-16 20:04 UTC, shacharmo commented on CTFd/api/v1/challenges.py
>              log(
Should use logger with log level, logger instance should also be be per module (in this case `challenges`)

2024-12-16 20:04 UTC, shacharmo commented on CTFd/utils/initialization/__init__.py
> +        "%(asctime)s|CTFd|%(levelname)s|%(message)s|%(event)s|extra_data=%(extra_data)s|trace_id=%(trace_id)s"
CTFd shouldn't be hardcoded, we already know were are in the context of CTFd, instead it should be the module which created the log

2024-12-16 20:04 UTC, shacharmo commented on CTFd/utils/user/user_manager.py
> +        idp_fields = ['name', 'email','custom:active_c' 'type', 'secret', 'website', 'affiliation', 'country', 'hidden', 'banned', 'verified', 'language']
Use a better name like `current_challenge` for clarity

2024-12-16 20:04 UTC, shacharmo commented on CTFd/utils/logging/__init__.py
> +    print('now logging')
Remove

2024-12-16 20:04 UTC, shacharmo commented on CTFd/utils/security/auth.py
> +def replaceCognitoSubInUserId(sub):
Isn't there a linter defined? There should be at least one empty row before this line

2024-12-17 11:45 UTC, tomerp20 commented on CTFd/api/v1/challenges.py
> +                submission = submission,
the stage (challange) id is added inside the log() function.
kpm added.

2024-12-17 11:46 UTC, tomerp20 commented on CTFd/utils/logging/__init__.py
> +        "trace_id": 123123,
Yes, the trace_id will be there in the next pr (:

2024-12-17 13:05 UTC, tomerp20 commented on CTFd/api/v1/challenges.py
> +                    "correct_stage_solve",
added kmp

2024-12-19 14:47 UTC, tomerp20 commented on CTFd/api/v1/challenges.py
>              log(
fixed

2024-12-19 14:47 UTC, tomerp20 commented on CTFd/utils/initialization/__init__.py
> +    # logger_logins = logging.getLogger("logins")
fixed

2024-12-19 14:50 UTC, merged